"""add expected_dividend_yield to accounts

Revision ID: 8c93f34ff5e4
Revises: a914aea1b851
Create Date: 2026-05-06 17:06:13.911991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c93f34ff5e4'
down_revision = 'a914aea1b851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_dividend_yield', sa.Numeric(precision=7, scale=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('expected_dividend_yield')

    # ### end Alembic commands ###
