"""add apy to accounts

Revision ID: a914aea1b851
Revises: b2c3d4e5f6a1
Create Date: 2026-05-03 19:41:45.539149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a914aea1b851'
down_revision = 'b2c3d4e5f6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if 'hysa_accounts' in sa.inspect(bind).get_table_names():
        op.drop_table('hysa_accounts')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apy', sa.Numeric(precision=7, scale=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('apy')

    op.create_table('hysa_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('institution', sa.VARCHAR(length=100), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=14, scale=2), nullable=False),
    sa.Column('apy', sa.NUMERIC(precision=7, scale=5), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
