"""add account management fields

Revision ID: d314a7d176e6
Revises: 
Create Date: 2026-03-04 16:58:30.726781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd314a7d176e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('institution', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('display_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('display_color')
        batch_op.drop_column('is_active')
        batch_op.drop_column('notes')
        batch_op.drop_column('account_number')
        batch_op.drop_column('institution')
        batch_op.drop_column('tax_status')

    # ### end Alembic commands ###
