"""add updated_at to spending_entries

Revision ID: ea70ad5d7726
Revises: e5f6a1b2c3d4
Create Date: 2026-04-18 06:22:22.002623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea70ad5d7726'
down_revision = 'e5f6a1b2c3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spending_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spending_entries', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
